"use client";
import { Database, Monitor, Moon, Sun } from "lucide-react";
import { FieldOpsThemeToggle } from "@/components/fieldops-theme-toggle";
import type { DbSettings } from "../types";
import { formatDateTime } from "../utils";
import { SectionCard } from "./section-card";
export function AppearancePanel({ settings, currentUserName }: { settings:DbSettings|null; currentUserName:string }) {
  return <div className="space-y-5"><SectionCard title="Appearance" description="Theme preference is local to this browser and does not change another user's display."><div className="flex flex-wrap items-center justify-between gap-4 border border-border p-4"><div><div className="flex items-center gap-2 text-sm font-black"><Sun className="h-4 w-4"/>Day <span className="text-muted-foreground">/</span> <Moon className="h-4 w-4"/>Night</div><div className="mt-1 text-xs text-muted-foreground">Use the existing FieldOps theme switcher.</div></div><FieldOpsThemeToggle/></div></SectionCard><SectionCard title="System"><div className="grid gap-3 md:grid-cols-2"><div className="border border-border p-4"><div className="flex items-center gap-2 text-xs font-black uppercase text-muted-foreground"><Database className="h-4 w-4"/>Data source</div><div className="mt-2 text-sm font-black">Supabase · Connected</div></div><div className="border border-border p-4"><div className="flex items-center gap-2 text-xs font-black uppercase text-muted-foreground"><Monitor className="h-4 w-4"/>Signed in as</div><div className="mt-2 text-sm font-black">{currentUserName}</div></div><div className="border border-border p-4"><div className="text-xs font-black uppercase text-muted-foreground">Settings updated</div><div className="mt-2 text-sm font-black">{formatDateTime(settings?.updated_at)}</div></div><div className="border border-border p-4"><div className="text-xs font-black uppercase text-muted-foreground">System timezone</div><div className="mt-2 text-sm font-black">{settings?.timezone||"America/Vancouver"}</div></div></div></SectionCard></div>;
}
