"use client";

import { X } from "lucide-react";
import type { Dispatch, SetStateAction } from "react";
import type { CertificationForm } from "../../types";

export function CertificationModal({ open, form, setForm, saving, error, onSave, onClose }: { open: boolean; form: CertificationForm; setForm: Dispatch<SetStateAction<CertificationForm>>; saving: boolean; error: string | null; onSave: () => void; onClose: () => void }) {
  if (!open) return null;
  const fieldClass = "mt-1 h-10 w-full border border-border bg-background px-3 text-sm outline-none focus:border-primary";
  return <div className="fixed inset-0 z-[91000] flex items-center justify-center p-4"><button type="button" aria-label="Close certification" onClick={onClose} className="absolute inset-0 bg-black/55" /><section className="relative z-10 flex max-h-[90vh] w-full max-w-[720px] flex-col overflow-hidden border border-border bg-background shadow-2xl"><div className="flex items-center justify-between border-b border-border px-5 py-4"><h2 className="text-lg font-black">Add Certification</h2><button type="button" onClick={onClose} className="flex h-9 w-9 items-center justify-center border border-border"><X className="h-4 w-4" /></button></div><div className="flex-1 overflow-y-auto p-5">{error && <div className="mb-4 border border-rose-500/40 bg-rose-500/10 p-3 text-sm text-rose-500">{error}</div>}<div className="grid gap-4 md:grid-cols-2"><label className="text-xs font-bold md:col-span-2">Certification name<input value={form.certificationName} onChange={(e) => setForm((current) => ({ ...current, certificationName: e.target.value }))} className={fieldClass} /></label><label className="text-xs font-bold">Issuer<input value={form.issuer} onChange={(e) => setForm((current) => ({ ...current, issuer: e.target.value }))} className={fieldClass} /></label><label className="text-xs font-bold">Credential number<input value={form.credentialNumber} onChange={(e) => setForm((current) => ({ ...current, credentialNumber: e.target.value }))} className={fieldClass} /></label><label className="text-xs font-bold">Issued on<input type="date" value={form.issuedOn} onChange={(e) => setForm((current) => ({ ...current, issuedOn: e.target.value }))} className={fieldClass} /></label><label className="text-xs font-bold">Expires on<input type="date" value={form.expiresOn} onChange={(e) => setForm((current) => ({ ...current, expiresOn: e.target.value }))} className={fieldClass} /></label><label className="text-xs font-bold md:col-span-2">Notes<textarea value={form.notes} onChange={(e) => setForm((current) => ({ ...current, notes: e.target.value }))} className="mt-1 min-h-24 w-full border border-border bg-background p-3 text-sm outline-none focus:border-primary" /></label></div></div><div className="flex justify-end gap-2 border-t border-border px-5 py-4"><button type="button" onClick={onClose} className="h-10 border border-border px-4 text-sm font-black">Cancel</button><button type="button" onClick={onSave} disabled={saving} className="h-10 bg-primary px-5 text-sm font-black text-primary-foreground disabled:opacity-60">{saving ? "Saving…" : "Add Certification"}</button></div></section></div>;
}
