"use client";

import { X } from "lucide-react";
import type { Dispatch, SetStateAction } from "react";
import type { CompensationForm } from "../../types";

export function CompensationModal({ open, form, setForm, saving, error, onSave, onClose }: { open: boolean; form: CompensationForm; setForm: Dispatch<SetStateAction<CompensationForm>>; saving: boolean; error: string | null; onSave: () => void; onClose: () => void }) {
  if (!open) return null;
  const fieldClass = "mt-1 h-10 w-full border border-border bg-background px-3 text-sm outline-none focus:border-primary";
  return <div className="fixed inset-0 z-[91000] flex items-center justify-center p-4"><button type="button" aria-label="Close rates" onClick={onClose} className="absolute inset-0 bg-black/55" /><section className="relative z-10 w-full max-w-[620px] border border-border bg-background shadow-2xl"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="text-lg font-black">Default Technician Rates</h2><p className="mt-1 text-xs text-muted-foreground">Billing and pay remain separate.</p></div><button type="button" onClick={onClose} className="flex h-9 w-9 items-center justify-center border border-border"><X className="h-4 w-4" /></button></div><div className="p-5">{error && <div className="mb-4 border border-rose-500/40 bg-rose-500/10 p-3 text-sm text-rose-500">{error}</div>}<div className="grid gap-4 md:grid-cols-3"><label className="text-xs font-bold">Billing / hour<input type="number" min="0" step="0.01" value={form.billingRate} onChange={(e) => setForm((current) => ({ ...current, billingRate: e.target.value }))} className={fieldClass} /></label><label className="text-xs font-bold">Pay / hour<input type="number" min="0" step="0.01" value={form.payRate} onChange={(e) => setForm((current) => ({ ...current, payRate: e.target.value }))} className={fieldClass} /></label><label className="text-xs font-bold">Currency<input maxLength={3} value={form.currency} onChange={(e) => setForm((current) => ({ ...current, currency: e.target.value.toUpperCase() }))} className={fieldClass} /></label></div><div className="mt-4 border border-border bg-muted/20 p-3 text-xs text-muted-foreground">These are defaults for future actual-time records. Time entries keep their own captured rates so later default-rate changes do not rewrite historical work.</div></div><div className="flex justify-end gap-2 border-t border-border px-5 py-4"><button type="button" onClick={onClose} className="h-10 border border-border px-4 text-sm font-black">Cancel</button><button type="button" onClick={onSave} disabled={saving} className="h-10 bg-primary px-5 text-sm font-black text-primary-foreground disabled:opacity-60">{saving ? "Saving…" : "Save Rates"}</button></div></section></div>;
}
