"use client";

import { X } from "lucide-react";
import type { Dispatch, SetStateAction } from "react";
import type { ScheduleEventForm } from "../../types";
import { scheduleEventTypes } from "../../constants";
import { capitalize } from "../../utils";

export function ScheduleEventModal({ open, form, setForm, saving, error, onSave, onClose }: { open: boolean; form: ScheduleEventForm; setForm: Dispatch<SetStateAction<ScheduleEventForm>>; saving: boolean; error: string | null; onSave: () => void; onClose: () => void }) {
  if (!open) return null;
  const fieldClass = "mt-1 h-10 w-full border border-border bg-background px-3 text-sm outline-none focus:border-primary";
  return <div className="fixed inset-0 z-[91000] flex items-center justify-center p-4"><button type="button" aria-label="Close schedule event" onClick={onClose} className="absolute inset-0 bg-black/55" /><section className="relative z-10 w-full max-w-[720px] border border-border bg-background shadow-2xl"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="text-lg font-black">Add Schedule Event</h2><p className="mt-1 text-xs text-muted-foreground">Block non-job time on the technician schedule.</p></div><button type="button" onClick={onClose} className="flex h-9 w-9 items-center justify-center border border-border"><X className="h-4 w-4" /></button></div><div className="p-5">{error && <div className="mb-4 border border-rose-500/40 bg-rose-500/10 p-3 text-sm text-rose-500">{error}</div>}<div className="grid gap-4 md:grid-cols-2"><label className="text-xs font-bold">Event type<select value={form.eventType} onChange={(e) => setForm((current) => ({ ...current, eventType: e.target.value }))} className={fieldClass}>{scheduleEventTypes.map((item) => <option key={item} value={item}>{capitalize(item)}</option>)}</select></label><label className="text-xs font-bold">Title<input value={form.title} onChange={(e) => setForm((current) => ({ ...current, title: e.target.value }))} className={fieldClass} placeholder="Vacation, Safety training..." /></label><label className="text-xs font-bold">Date<input type="date" value={form.date} onChange={(e) => setForm((current) => ({ ...current, date: e.target.value }))} className={fieldClass} /></label><div className="grid grid-cols-2 gap-2"><label className="text-xs font-bold">Start<input type="time" value={form.startTime} onChange={(e) => setForm((current) => ({ ...current, startTime: e.target.value }))} className={fieldClass} /></label><label className="text-xs font-bold">End<input type="time" value={form.endTime} onChange={(e) => setForm((current) => ({ ...current, endTime: e.target.value }))} className={fieldClass} /></label></div><label className="text-xs font-bold md:col-span-2">Notes<textarea value={form.notes} onChange={(e) => setForm((current) => ({ ...current, notes: e.target.value }))} className="mt-1 min-h-24 w-full border border-border bg-background p-3 text-sm outline-none focus:border-primary" /></label></div><div className="mt-4 border border-amber-500/30 bg-amber-500/10 p-3 text-xs text-amber-700 dark:text-amber-300">A schedule block cannot overlap another active FieldOps schedule item. Reassign/reschedule work first when necessary.</div></div><div className="flex justify-end gap-2 border-t border-border px-5 py-4"><button type="button" onClick={onClose} className="h-10 border border-border px-4 text-sm font-black">Cancel</button><button type="button" onClick={onSave} disabled={saving} className="h-10 bg-primary px-5 text-sm font-black text-primary-foreground disabled:opacity-60">{saving ? "Saving…" : "Add Event"}</button></div></section></div>;
}
