import { History, X } from "lucide-react";
import type { Dispatch, SetStateAction } from "react";
import type { DbProfile, DbTimeCorrection, DbTimeEntry, DbWorkOrder, ServerAvailability, TimeEditorForm } from "../../types";
import { dateTimeLocalInputFromIso, dateTimePartDate, dateTimePartTime, formatAvailabilityWindows, formatLocalDateTime24, isTerminalWorkOrderStatus, mergeDateTimeClock, mergeDateTimeParts, minutesLabel, statusLabel } from "../../utils";

type Props = { selectedOrder:DbWorkOrder; editingTimeEntryId:string|null; editingTimeEntry:DbTimeEntry|null; timeEditorForm:TimeEditorForm; setTimeEditorForm:Dispatch<SetStateAction<TimeEditorForm>>; timeEditorError:string|null; savingTimeEditor:boolean; technicians:DbProfile[]; serverAvailability:Map<string,ServerAvailability>; serverAvailabilityLoading:boolean; serverAvailabilityError:string|null; timeEditorPlannedStartIso:string|null; timeEditorPlannedEndIso:string|null; timeEditorPlannedMinutes:number|null; timeEditorRecordedMinutes:number|null; timeEditorActualMinutes:number|null; timeEditorVariance:string; timeCorrections:DbTimeCorrection[]; profileMap:Map<string,DbProfile>; defaultCustomerBillingRate:number; defaultTechnicianPayRate:number; onClose:()=>void; onSave:()=>void; };

function stringValue(value:unknown){ return typeof value==="string"?value:value==null?null:String(value); }
function correctionWindow(values:Record<string,unknown>|null){ if(!values)return "—"; const activity=statusLabel(stringValue(values.activity_type)??"work"); const start=stringValue(values.started_at); const end=stringValue(values.ended_at); if(!start)return activity; return `${activity} · ${formatLocalDateTime24(start)} → ${end?formatLocalDateTime24(end):"ACTIVE"}`; }

export function TechnicianTimeModal(props:Props){
  const {selectedOrder,editingTimeEntryId,editingTimeEntry,timeEditorForm,setTimeEditorForm,timeEditorError,savingTimeEditor,technicians,serverAvailability,serverAvailabilityLoading,serverAvailabilityError,timeEditorPlannedStartIso,timeEditorPlannedEndIso,timeEditorPlannedMinutes,timeEditorRecordedMinutes,timeEditorActualMinutes,timeEditorVariance,timeCorrections,profileMap,defaultCustomerBillingRate,defaultTechnicianPayRate,onClose,onSave}=props;
  return <div className="fixed inset-0 z-[120000] flex items-center justify-center p-4">
    <button type="button" aria-label="Close time editor" onClick={()=>{if(!savingTimeEditor)onClose();}} className="absolute inset-0 bg-black/60"/>
    <section className="relative z-10 flex max-h-[90vh] w-full max-w-[820px] flex-col overflow-hidden rounded-2xl border border-border bg-background shadow-2xl">
      <div className="flex items-start justify-between gap-4 border-b border-border px-5 py-4"><div><div className="text-xs font-black text-primary">ADMIN / MANAGER CONTROL</div><h3 className="mt-1 text-lg font-bold">{editingTimeEntryId?"Correct Technician Time":"Add Technician Time Segment"}</h3><div className="mt-1 text-sm text-muted-foreground">{selectedOrder.work_order_number} · {selectedOrder.title}</div></div><button type="button" disabled={savingTimeEditor} onClick={onClose} className="flex h-9 w-9 items-center justify-center rounded-lg border border-border"><X className="h-4 w-4"/></button></div>
      <div className="flex-1 overflow-y-auto p-5">
        {timeEditorError?<div className="mb-4 rounded-xl border border-rose-500/50 bg-rose-950 px-4 py-3 text-sm font-semibold text-rose-100">{timeEditorError}</div>:null}
        <section className="mb-5 overflow-hidden rounded-xl border border-border bg-muted/25"><div className="border-b border-border px-4 py-2.5"><div className="text-[10px] font-black uppercase tracking-wider text-muted-foreground">Work Order Schedule</div></div><div className="grid grid-cols-3 divide-x divide-border"><div className="p-3"><div className="text-[9px] font-black uppercase text-muted-foreground">Scheduled Start</div><div className="mt-1 text-xs font-bold">{timeEditorPlannedStartIso?formatLocalDateTime24(timeEditorPlannedStartIso):"Not set"}</div></div><div className="p-3"><div className="text-[9px] font-black uppercase text-muted-foreground">Scheduled End</div><div className="mt-1 text-xs font-bold">{timeEditorPlannedEndIso?formatLocalDateTime24(timeEditorPlannedEndIso):"Not set"}</div></div><div className="p-3"><div className="text-[9px] font-black uppercase text-muted-foreground">Planned Duration</div><div className="mt-1 text-xs font-black text-primary">{minutesLabel(timeEditorPlannedMinutes)}</div></div></div></section>
        {editingTimeEntry?<div className="mb-4 rounded-xl border border-border bg-card px-4 py-3 text-xs"><span className="font-black">Editing recorded segment:</span> {statusLabel(editingTimeEntry.activity_type)} · {formatLocalDateTime24(editingTimeEntry.started_at)} → {editingTimeEntry.ended_at?formatLocalDateTime24(editingTimeEntry.ended_at):"ACTIVE"}{editingTimeEntry.ended_at?` · ${minutesLabel(timeEditorRecordedMinutes)}`:""}</div>:null}
        <div className="grid gap-4 md:grid-cols-2">
          <label className="md:col-span-2"><span className="mb-1.5 block text-xs font-bold">Technician</span>{serverAvailabilityError?<div className="mb-2 rounded-xl border border-rose-500/40 bg-rose-500/10 px-3 py-2 text-[10px] font-bold text-rose-500">Availability could not be verified from the database.</div>:null}<select value={timeEditorForm.technicianId} disabled={editingTimeEntryId!==null} onChange={e=>setTimeEditorForm(current=>({...current,technicianId:e.target.value,billingRate:String(defaultCustomerBillingRate??0),payRate:String(defaultTechnicianPayRate??0)}))} className="h-11 w-full rounded-xl border border-border bg-card px-3 text-sm disabled:opacity-60">{technicians.map(technician=>{const a=serverAvailability.get(technician.id);const label=serverAvailabilityLoading?"Checking availability…":a?formatAvailabilityWindows(a.free_windows):"Availability unavailable";return <option key={technician.id} value={technician.id}>{technician.full_name??technician.email??"Technician"} — {label}</option>;})}</select></label>
          <div><span className="mb-1.5 block text-xs font-bold">Actual Start</span><div className="grid grid-cols-[1fr_132px] gap-2"><label><span className="mb-1 block text-[9px] font-black uppercase text-muted-foreground">Date</span><input type="date" value={dateTimePartDate(timeEditorForm.startedAt)} onChange={e=>setTimeEditorForm(current=>({...current,startedAt:mergeDateTimeParts(current.startedAt,"date",e.target.value)}))} className="h-11 w-full rounded-xl border border-border bg-card px-2 text-sm"/></label><label><span className="mb-1 block text-[9px] font-black uppercase text-muted-foreground">Time</span><input type="time" step="60" value={dateTimePartTime(timeEditorForm.startedAt)} onChange={e=>setTimeEditorForm(current=>({...current,startedAt:mergeDateTimeClock(current.startedAt,e.target.value)}))} className="h-11 w-full rounded-xl border border-border bg-card px-2 text-sm"/></label></div></div>
          <div><span className="mb-1.5 block text-xs font-bold">Actual End</span><div className="grid grid-cols-[1fr_132px] gap-2"><label><span className="mb-1 block text-[9px] font-black uppercase text-muted-foreground">Date</span><input type="date" value={dateTimePartDate(timeEditorForm.endedAt)} onChange={e=>setTimeEditorForm(current=>({...current,endedAt:mergeDateTimeParts(current.endedAt,"date",e.target.value)}))} className="h-11 w-full rounded-xl border border-border bg-card px-2 text-sm"/></label><label><span className="mb-1 block text-[9px] font-black uppercase text-muted-foreground">Time</span><input type="time" step="60" disabled={!timeEditorForm.endedAt} value={dateTimePartTime(timeEditorForm.endedAt)} onChange={e=>setTimeEditorForm(current=>({...current,endedAt:mergeDateTimeClock(current.endedAt,e.target.value)}))} className="h-11 w-full rounded-xl border border-border bg-card px-2 text-sm disabled:opacity-50"/></label></div>{!isTerminalWorkOrderStatus(selectedOrder.status)?<button type="button" onClick={()=>setTimeEditorForm(current=>({...current,endedAt:current.endedAt?"":dateTimeLocalInputFromIso(timeEditorPlannedEndIso)}))} className="mt-2 rounded-lg border border-border px-2 py-1 text-[10px] font-bold hover:bg-muted">{timeEditorForm.endedAt?"Mark Active / No End":"Restore Planned End"}</button>:null}</div>
          <label><span className="mb-1.5 block text-xs font-bold">Activity</span><select value={timeEditorForm.activityType} onChange={e=>{const next=e.target.value;setTimeEditorForm(current=>({...current,activityType:next,billable:next==="break"?false:current.activityType==="break"?true:current.billable}));}} className="h-11 w-full rounded-xl border border-border bg-card px-3 text-sm"><option value="travel">Travel</option><option value="on_site">On Site</option><option value="work">Work / Labour</option><option value="waiting">Waiting</option><option value="break">Break / Lunch</option><option value="other">Other</option></select></label>
          <label className="flex items-center gap-3 rounded-xl border border-border px-3 py-3"><input type="checkbox" checked={timeEditorForm.billable} onChange={e=>setTimeEditorForm(current=>({...current,billable:e.target.checked}))}/><span><span className="block text-xs font-bold">Billable labour</span><span className="block text-[10px] text-muted-foreground">Breaks/waiting can be marked non-billable.</span></span></label>
          <label><span className="mb-1.5 block text-xs font-bold">Customer Billing Rate</span><input type="number" min="0" step="0.01" value={timeEditorForm.billingRate} onChange={e=>setTimeEditorForm(current=>({...current,billingRate:e.target.value}))} className="h-11 w-full rounded-xl border border-border bg-card px-3 text-sm"/><span className="mt-1 block text-[10px] text-muted-foreground">Settings default: ${Number(defaultCustomerBillingRate||0).toFixed(2)} / h · editable here</span></label>
          <label><span className="mb-1.5 block text-xs font-bold">Technician Pay Rate</span><input type="number" min="0" step="0.01" value={timeEditorForm.payRate} onChange={e=>setTimeEditorForm(current=>({...current,payRate:e.target.value}))} className="h-11 w-full rounded-xl border border-border bg-card px-3 text-sm"/><span className="mt-1 block text-[10px] text-muted-foreground">Settings default: ${Number(defaultTechnicianPayRate||0).toFixed(2)} / h · editable here</span></label>
          <section className="md:col-span-2 rounded-xl border border-primary/30 bg-primary/[0.04]"><div className="grid grid-cols-3 divide-x divide-border"><div className="p-3"><div className="text-[9px] font-black uppercase text-muted-foreground">Actual Duration</div><div className="mt-1 text-xs font-black text-primary">{timeEditorActualMinutes===null?"Not available":minutesLabel(timeEditorActualMinutes)}</div></div><div className="p-3"><div className="text-[9px] font-black uppercase text-muted-foreground">Vs Planned</div><div className="mt-1 text-xs font-black">{timeEditorVariance}</div></div><div className="p-3"><div className="text-[9px] font-black uppercase text-muted-foreground">Recorded Before</div><div className="mt-1 text-xs font-black">{editingTimeEntry?.ended_at?minutesLabel(timeEditorRecordedMinutes):editingTimeEntry?"ACTIVE":"New segment"}</div></div></div></section>
          <label className="md:col-span-2"><span className="mb-1.5 block text-xs font-bold">Correction Reason <span className="text-rose-500">*</span></span><textarea rows={3} value={timeEditorForm.reason} onChange={e=>setTimeEditorForm(current=>({...current,reason:e.target.value}))} placeholder="e.g. Technician forgot to clock out; confirmed end time with supervisor." className="w-full rounded-xl border border-border bg-card p-3 text-sm"/></label>
        </div>
        <section className="mt-5 overflow-hidden rounded-xl border border-border"><div className="flex items-center gap-2 border-b border-border bg-muted/30 px-4 py-3"><History className="h-4 w-4 text-primary"/><div><div className="text-xs font-black">Time Edit History</div><div className="text-[10px] text-muted-foreground">Added/corrected activities with before and after time.</div></div></div>{timeCorrections.length===0?<div className="px-4 py-5 text-sm text-muted-foreground">No manual time edits recorded for this Work Order yet.</div>:<div className="divide-y divide-border">{timeCorrections.map(c=>{const by=profileMap.get(c.corrected_by);return <div key={c.id} className="grid gap-2 px-4 py-3 text-xs md:grid-cols-[1fr_1fr_170px]"><div><div className="text-[9px] font-black uppercase text-muted-foreground">Before</div><div className="mt-1 font-bold">{c.operation==="added"?"New segment":correctionWindow(c.original_values)}</div></div><div><div className="text-[9px] font-black uppercase text-muted-foreground">After</div><div className="mt-1 font-bold text-primary">{correctionWindow(c.corrected_values)}</div></div><div><div className="text-[9px] font-black uppercase text-muted-foreground">Audit</div><div className="mt-1 font-bold">{by?.full_name??by?.email??"Admin / Manager"}</div><div className="text-[10px] text-muted-foreground">{formatLocalDateTime24(c.corrected_at)}</div><div className="mt-1 text-[10px] text-muted-foreground">{c.reason}</div></div></div>;})}</div>}</section>
      </div>
      <div className="flex flex-wrap items-center justify-between gap-3 border-t border-border bg-background p-4"><div className="min-w-0 flex-1">{timeEditorError?<div className="text-xs font-bold text-rose-500">{timeEditorError}</div>:timeEditorForm.reason.trim().length<5?<div className="text-xs font-bold text-amber-600 dark:text-amber-300">Correction reason is required before saving.</div>:<div className="text-xs font-bold text-emerald-600 dark:text-emerald-400">Ready to save.</div>}</div><div className="flex gap-2"><button type="button" disabled={savingTimeEditor} onClick={onClose} className="h-10 rounded-xl border border-border px-4 text-sm font-bold">Cancel</button><button type="button" disabled={savingTimeEditor} onClick={onSave} className="h-10 rounded-xl bg-primary px-5 text-sm font-bold text-primary-foreground disabled:opacity-40">{savingTimeEditor?"Saving…":editingTimeEntryId?"Save Correction":"Add Time Segment"}</button></div></div>
    </section>
  </div>;
}
