"use client";

import type { ReactNode } from "react";
import type { DbSupplier, InventoryItemForm } from "../../types";
import { ModalShell } from "../modal-shell";

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block"><span className="mb-1 block text-[10px] font-black uppercase text-muted-foreground">{label}</span>{children}</label>; }
const input = "h-10 w-full border border-border bg-background px-3 text-sm outline-none focus:border-primary";

export function InventoryItemFormModal({ mode, form, suppliers, error, saving, onChange, onSave, onClose }: { mode: "create" | "edit"; form: InventoryItemForm; suppliers: DbSupplier[]; error: string | null; saving: boolean; onChange: (form: InventoryItemForm) => void; onSave: () => void; onClose: () => void }) {
  return <ModalShell title={mode === "create" ? "New Inventory Item" : "Edit Inventory Item"} subtitle="Quantity-based stock only. Serialized equipment belongs in Assets." onClose={onClose} footer={<div className="flex justify-end gap-2"><button onClick={onClose} className="h-10 border border-border px-4 text-xs font-black">Cancel</button><button disabled={saving} onClick={onSave} className="h-10 bg-primary px-4 text-xs font-black text-primary-foreground disabled:opacity-60">{saving?"Saving…":mode==="create"?"Create Item":"Save Changes"}</button></div>}>
    <div className="grid gap-4 md:grid-cols-2"><Field label="Item Name"><input className={input} value={form.name} onChange={e=>onChange({...form,name:e.target.value})} /></Field><Field label="SKU"><input className={input} value={form.sku} onChange={e=>onChange({...form,sku:e.target.value})} /></Field><Field label="Part Number"><input className={input} value={form.partNumber} onChange={e=>onChange({...form,partNumber:e.target.value})} /></Field><Field label="Barcode"><input className={input} value={form.barcode} onChange={e=>onChange({...form,barcode:e.target.value})} /></Field><Field label="Category"><input className={input} value={form.category} onChange={e=>onChange({...form,category:e.target.value})} /></Field><Field label="Manufacturer"><input className={input} value={form.manufacturer} onChange={e=>onChange({...form,manufacturer:e.target.value})} /></Field><Field label="Unit"><input className={input} value={form.unit} onChange={e=>onChange({...form,unit:e.target.value})} placeholder="each, box, ft, kg..." /></Field><Field label="Preferred Supplier"><select className={input} value={form.preferredSupplierId} onChange={e=>onChange({...form,preferredSupplierId:e.target.value})}><option value="">None</option>{suppliers.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Unit Cost"><input type="number" min="0" step="0.01" className={input} value={form.unitCost} onChange={e=>onChange({...form,unitCost:e.target.value})} /></Field><Field label="Unit Price"><input type="number" min="0" step="0.01" className={input} value={form.unitPrice} onChange={e=>onChange({...form,unitPrice:e.target.value})} /></Field><Field label="Reorder Level"><input type="number" min="0" step="0.01" className={input} value={form.reorderLevel} onChange={e=>onChange({...form,reorderLevel:e.target.value})} /></Field><Field label="Reorder Quantity"><input type="number" min="0" step="0.01" className={input} value={form.reorderQuantity} onChange={e=>onChange({...form,reorderQuantity:e.target.value})} /></Field></div>
    <div className="mt-4"><Field label="Description"><textarea className="min-h-20 w-full border border-border bg-background p-3 text-sm" value={form.description} onChange={e=>onChange({...form,description:e.target.value})} /></Field></div>
    <div className="mt-4"><Field label="Internal Notes"><textarea className="min-h-20 w-full border border-border bg-background p-3 text-sm" value={form.notes} onChange={e=>onChange({...form,notes:e.target.value})} /></Field></div>
    <div className="mt-4 flex flex-wrap gap-5 text-xs font-bold"><label className="flex items-center gap-2"><input type="checkbox" checked={form.trackStock} onChange={e=>onChange({...form,trackStock:e.target.checked})}/> Track stock quantity</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.taxable} onChange={e=>onChange({...form,taxable:e.target.checked})}/> Taxable</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.active} onChange={e=>onChange({...form,active:e.target.checked})}/> Active</label></div>
    {error && <div className="mt-4 border border-rose-500/40 bg-rose-500/10 p-3 text-xs font-semibold text-rose-600 dark:text-rose-300">{error}</div>}
  </ModalShell>;
}
