"use client";
import { Plus, Trash2 } from "lucide-react";
import type { DbInventoryItem, DbSupplier, PurchaseOrderForm } from "../../types";
import { ModalShell } from "../modal-shell";
const input="h-10 w-full border border-border bg-background px-3 text-sm";
export function PurchaseOrderModal({ form, suppliers, items, error, saving, onChange, onSave, onClose }: { form:PurchaseOrderForm; suppliers:DbSupplier[]; items:DbInventoryItem[]; error:string|null; saving:boolean; onChange:(f:PurchaseOrderForm)=>void; onSave:()=>void; onClose:()=>void }) { const setLine=(index:number,patch:Partial<PurchaseOrderForm['lines'][number]>)=>onChange({...form,lines:form.lines.map((l,i)=>i===index?{...l,...patch}:l)}); return <ModalShell title="New Purchase Order" subtitle="Create the PO first, then approve/order it from the PO details." wide onClose={onClose} footer={<div className="flex justify-end gap-2"><button onClick={onClose} className="h-10 border border-border px-4 text-xs font-black">Cancel</button><button disabled={saving} onClick={onSave} className="h-10 bg-primary px-4 text-xs font-black text-primary-foreground">{saving?"Creating…":"Create Purchase Order"}</button></div>}>
<div className="grid gap-4 md:grid-cols-4"><label className="md:col-span-2"><span className="mb-1 block text-[10px] font-black uppercase text-muted-foreground">Supplier</span><select className={input} value={form.supplierId} onChange={e=>onChange({...form,supplierId:e.target.value})}><option value="">Choose supplier</option>{suppliers.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label><span className="mb-1 block text-[10px] font-black uppercase text-muted-foreground">Expected Date</span><input type="date" className={input} value={form.expectedDate} onChange={e=>onChange({...form,expectedDate:e.target.value})}/></label><label><span className="mb-1 block text-[10px] font-black uppercase text-muted-foreground">Shipping</span><input type="number" min="0" step="0.01" className={input} value={form.shippingAmount} onChange={e=>onChange({...form,shippingAmount:e.target.value})}/></label><label><span className="mb-1 block text-[10px] font-black uppercase text-muted-foreground">Tax</span><input type="number" min="0" step="0.01" className={input} value={form.taxAmount} onChange={e=>onChange({...form,taxAmount:e.target.value})}/></label><label className="md:col-span-3"><span className="mb-1 block text-[10px] font-black uppercase text-muted-foreground">Notes</span><input className={input} value={form.notes} onChange={e=>onChange({...form,notes:e.target.value})}/></label></div>
<div className="mt-6 flex items-center justify-between"><div><div className="text-sm font-black">PO Lines</div><div className="text-[10px] text-muted-foreground">Quantity and supplier pricing are snapshotted on the PO.</div></div><button type="button" onClick={()=>onChange({...form,lines:[...form.lines,{itemId:"",quantity:"1",unitCost:"",supplierSku:""}]})} className="inline-flex h-9 items-center gap-2 border border-border px-3 text-xs font-black"><Plus className="h-3.5 w-3.5"/> Add Line</button></div>
<div className="mt-3 space-y-2">{form.lines.map((line,index)=><div key={index} className="grid gap-2 border border-border bg-card p-3 md:grid-cols-[1fr_120px_140px_180px_40px]"><select className={input} value={line.itemId} onChange={e=>{const item=items.find(i=>i.id===e.target.value);setLine(index,{itemId:e.target.value,unitCost:line.unitCost||item?.unit_cost.toString()||""})}}><option value="">Choose item</option>{items.filter(i=>i.active).map(i=><option key={i.id} value={i.id}>{i.name}{i.sku?` · ${i.sku}`:""}</option>)}</select><input type="number" min="0.01" step="0.01" className={input} value={line.quantity} onChange={e=>setLine(index,{quantity:e.target.value})} placeholder="Qty"/><input type="number" min="0" step="0.01" className={input} value={line.unitCost} onChange={e=>setLine(index,{unitCost:e.target.value})} placeholder="Unit cost"/><input className={input} value={line.supplierSku} onChange={e=>setLine(index,{supplierSku:e.target.value})} placeholder="Supplier SKU"/><button disabled={form.lines.length===1} onClick={()=>onChange({...form,lines:form.lines.filter((_,i)=>i!==index)})} className="flex h-10 items-center justify-center border border-border text-rose-500 disabled:opacity-30"><Trash2 className="h-4 w-4"/></button></div>)}</div>{error&&<div className="mt-4 border border-rose-500/40 bg-rose-500/10 p-3 text-xs font-semibold text-rose-600 dark:text-rose-300">{error}</div>}</ModalShell>; }
