"use client";

import { ChevronRight } from "lucide-react";
import type { DbPurchaseOrder, DbPurchaseOrderItem, DbSupplier } from "../types";
import { capitalize, formatDate, money, purchaseOrderStatusTone } from "../utils";

export function PurchaseOrdersTable({ orders, lines, supplierMap, onOpen }: { orders: DbPurchaseOrder[]; lines: DbPurchaseOrderItem[]; supplierMap: Map<string, DbSupplier>; onOpen: (id: string) => void }) {
  if (!orders.length) return <div className="border border-border bg-card p-8 text-center text-sm text-muted-foreground">No purchase orders yet.</div>;
  return <div className="overflow-x-auto border border-border bg-card"><table className="w-full min-w-[980px] text-left"><thead className="bg-muted/40 text-[10px] font-black uppercase text-muted-foreground"><tr><th className="px-4 py-3">PO</th><th className="px-4 py-3">Supplier</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Expected</th><th className="px-4 py-3">Ordered</th><th className="px-4 py-3">Received</th><th className="px-4 py-3">Subtotal</th><th className="px-4 py-3 text-right">View</th></tr></thead><tbody>{orders.map((po) => { const poLines = lines.filter((l) => l.purchase_order_id === po.id); const subtotal = poLines.reduce((s,l)=>s+l.quantity_ordered*l.unit_cost,0); const ordered = poLines.reduce((s,l)=>s+l.quantity_ordered,0); const received=poLines.reduce((s,l)=>s+l.quantity_received,0); return <tr key={po.id} className="border-t border-border hover:bg-row-hover"><td className="px-4 py-4 text-sm font-black">{po.po_number}</td><td className="px-4 py-4 text-xs font-bold">{supplierMap.get(po.supplier_id)?.name ?? "Unknown supplier"}</td><td className="px-4 py-4"><span className={`border px-2 py-1 text-[9px] font-black uppercase ${purchaseOrderStatusTone(po.status)}`}>{capitalize(po.status)}</span></td><td className="px-4 py-4 text-xs">{formatDate(po.expected_date)}</td><td className="px-4 py-4 text-xs font-bold">{ordered}</td><td className="px-4 py-4 text-xs font-bold">{received}</td><td className="px-4 py-4 text-xs font-black">{money(subtotal + po.shipping_amount + po.tax_amount)}</td><td className="px-4 py-4 text-right"><button onClick={()=>onOpen(po.id)} className="inline-flex items-center gap-1 text-xs font-black text-primary">View <ChevronRight className="h-3.5 w-3.5" /></button></td></tr>; })}</tbody></table></div>;
}
