"use client";
import { AlertTriangle, Banknote, FileText, Plus, Printer, RefreshCw, RotateCcw, Send, ShieldCheck } from "lucide-react";
import type { DbCustomer, DbInvoice, DbInvoiceAdjustment, DbInvoiceEvent, DbInvoiceItem, DbPayment, DbProfile, DbSite, DbWorkOrder, InvoiceTab } from "../../types";
import { invoiceStatusLabels } from "../../constants";
import { effectiveInvoiceStatus, formatDate, formatDateTime, money, statusTone } from "../../utils";
import { ModalShell } from "../modal-shell";

function LineTable({ lines, currency }: { lines: DbInvoiceItem[]; currency: string }) {
  return <div className="overflow-x-auto border border-border"><table className="w-full min-w-[700px] text-left"><thead className="bg-muted/40 text-[10px] font-black uppercase text-muted-foreground"><tr><th className="px-3 py-2">Description</th><th className="px-3 py-2 text-right">Qty</th><th className="px-3 py-2 text-right">Unit price</th><th className="px-3 py-2 text-right">Total</th></tr></thead><tbody className="divide-y divide-border">{lines.length === 0 ? <tr><td colSpan={4} className="px-3 py-8 text-center text-sm text-muted-foreground">No items in this section.</td></tr> : lines.map((line) => <tr key={line.id}><td className="px-3 py-3"><div className="text-sm font-bold">{line.description}</div><div className="text-[10px] uppercase text-muted-foreground">{line.line_type}{line.taxable ? " · taxable" : ""}</div></td><td className="px-3 py-3 text-right text-sm">{Number(line.quantity).toFixed(2)}</td><td className="px-3 py-3 text-right text-sm">{money(line.unit_price, currency)}</td><td className="px-3 py-3 text-right text-sm font-black">{money(line.line_total, currency)}</td></tr>)}</tbody></table></div>;
}

export function InvoiceDetailModal({ invoice, customer, site, workOrder, items, payments, adjustments, events, profiles, today, tab, onTab, onClose, onEditTerms, onAddCharge, onAddAdjustment, onRecordPayment, onApprove, onSend, onVoidInvoice, onVoidPayment, canManageBilling, onRefreshFromWorkOrder }: {
  invoice: DbInvoice | null;
  customer: DbCustomer | null;
  site: DbSite | null;
  workOrder: DbWorkOrder | null;
  items: DbInvoiceItem[];
  payments: DbPayment[];
  adjustments: DbInvoiceAdjustment[];
  events: DbInvoiceEvent[];
  profiles: DbProfile[];
  today: string | null;
  tab: InvoiceTab;
  onTab: (tab: InvoiceTab) => void;
  onClose: () => void;
  onEditTerms: () => void;
  onAddCharge: () => void;
  onAddAdjustment: () => void;
  onRecordPayment: () => void;
  onApprove: () => void;
  onSend: () => void;
  onVoidInvoice: () => void;
  onVoidPayment: (payment: DbPayment) => void;
  canManageBilling: boolean;
  onRefreshFromWorkOrder: () => void;
}) {
  if (!invoice) return null;
  const status = effectiveInvoiceStatus(invoice, today);
  const profileMap = new Map(profiles.map((profile) => [profile.id, profile]));
  const labour = items.filter((line) => line.line_type === "labour");
  const materials = items.filter((line) => line.line_type === "material");
  const charges = items.filter((line) => !["labour", "material"].includes(line.line_type));
  const activeAdjustments = adjustments.filter((adjustment) => adjustment.status === "posted");
  const tabs: Array<{ key: InvoiceTab; label: string }> = [
    { key: "overview", label: "Overview" }, { key: "labour", label: "Labour" }, { key: "materials", label: "Materials" }, { key: "charges", label: "Charges" }, { key: "payments", label: "Payments" }, { key: "activity", label: "Activity" },
  ];
  return <ModalShell title={invoice.invoice_number} eyebrow="Invoice" onClose={onClose} width="max-w-6xl">
    <div className="no-print mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><span className={`px-2.5 py-1.5 text-[10px] font-black uppercase ${statusTone(status)}`}>{invoiceStatusLabels[status] ?? status}</span>{workOrder?.billing_status === "review_required" ? <span className="inline-flex items-center gap-1 bg-rose-500/15 px-2.5 py-1.5 text-[10px] font-black uppercase text-rose-700 dark:text-rose-300"><AlertTriangle className="h-3.5 w-3.5" /> Review required</span> : null}</div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => { onTab("overview"); window.setTimeout(() => window.print(), 60); }} className="inline-flex h-9 items-center gap-2 border border-border px-3 text-xs font-black hover:bg-muted"><Printer className="h-4 w-4" /> Print / PDF</button>{canManageBilling && invoice.status === "draft" && workOrder ? <button type="button" onClick={onRefreshFromWorkOrder} className="inline-flex h-9 items-center gap-2 border border-border px-3 text-xs font-black hover:bg-muted"><RefreshCw className="h-4 w-4" /> Refresh from Work Order</button> : null}{canManageBilling && invoice.status === "draft" ? <><button type="button" onClick={onEditTerms} className="h-9 border border-border px-3 text-xs font-black hover:bg-muted">Edit Terms</button><button type="button" onClick={onAddCharge} className="inline-flex h-9 items-center gap-2 border border-border px-3 text-xs font-black hover:bg-muted"><Plus className="h-4 w-4" /> Charge</button><button type="button" onClick={onApprove} className="inline-flex h-9 items-center gap-2 bg-primary px-3 text-xs font-black text-primary-foreground"><ShieldCheck className="h-4 w-4" /> Approve</button></> : null}{canManageBilling && ["approved", "ready"].includes(invoice.status) ? <button type="button" onClick={onSend} className="inline-flex h-9 items-center gap-2 bg-primary px-3 text-xs font-black text-primary-foreground"><Send className="h-4 w-4" /> Mark Sent</button> : null}{canManageBilling && invoice.status !== "draft" && invoice.status !== "void" ? <button type="button" onClick={onAddAdjustment} className="inline-flex h-9 items-center gap-2 border border-border px-3 text-xs font-black hover:bg-muted"><FileText className="h-4 w-4" /> Credit / Charge</button> : null}{canManageBilling && invoice.status !== "void" && invoice.balance_due > 0 && invoice.status !== "draft" ? <button type="button" onClick={onRecordPayment} className="inline-flex h-9 items-center gap-2 bg-emerald-600 px-3 text-xs font-black text-white"><Banknote className="h-4 w-4" /> Record Payment</button> : null}{canManageBilling && invoice.status !== "void" ? <button type="button" onClick={onVoidInvoice} className="inline-flex h-9 items-center gap-2 border border-rose-500/40 px-3 text-xs font-black text-rose-600 hover:bg-rose-500/10"><RotateCcw className="h-4 w-4" /> Void</button> : null}</div></div>
    <div className="no-print mb-5 flex flex-wrap gap-2 border-b border-border pb-3">{tabs.map((item) => <button key={item.key} type="button" onClick={() => onTab(item.key)} className={`px-3 py-2 text-xs font-black ${tab === item.key ? "bg-primary text-primary-foreground" : "border border-border hover:bg-muted"}`}>{item.label}</button>)}</div>

    <div id="fieldops-invoice-print">
      {tab === "overview" ? <div className="space-y-5">
        <div className="grid gap-4 md:grid-cols-2"><section className="border border-border p-4"><div className="text-[10px] font-black uppercase text-muted-foreground">Bill to</div><div className="mt-2 text-lg font-black">{invoice.customer_name_snapshot || customer?.name || "Customer"}</div><div className="mt-1 text-sm text-muted-foreground">{invoice.billing_email_snapshot || customer?.billing_email || "No billing email"}</div>{invoice.site_address_snapshot ? <div className="mt-2 whitespace-pre-line text-xs text-muted-foreground">{invoice.site_address_snapshot}</div> : site ? <div className="mt-2 text-xs text-muted-foreground">{[site.address1, site.address2, site.city, site.province_state, site.postal_code, site.country].filter(Boolean).join(", ")}</div> : null}</section><section className="border border-border p-4"><div className="grid grid-cols-2 gap-3 text-sm"><div><div className="text-[10px] font-black uppercase text-muted-foreground">Issued</div><div className="mt-1 font-bold">{formatDate(invoice.issued_date)}</div></div><div><div className="text-[10px] font-black uppercase text-muted-foreground">Due</div><div className="mt-1 font-bold">{formatDate(invoice.due_date)}</div></div><div><div className="text-[10px] font-black uppercase text-muted-foreground">Work Order</div><div className="mt-1 font-bold">{workOrder?.work_order_number ?? "—"}</div></div><div><div className="text-[10px] font-black uppercase text-muted-foreground">Customer PO</div><div className="mt-1 font-bold">{workOrder?.customer_po || "—"}</div></div></div></section></div>
        <LineTable lines={items} currency={invoice.currency} />
        {activeAdjustments.length > 0 ? <section className="border border-border p-4"><div className="mb-3 text-xs font-black uppercase">Adjustments</div><div className="space-y-2">{activeAdjustments.map((adjustment) => <div key={adjustment.id} className="flex items-center justify-between gap-4 text-sm"><div><span className="font-bold">{adjustment.adjustment_type === "credit" ? "Credit note" : "Additional charge"}</span><span className="ml-2 text-muted-foreground">{adjustment.reason}</span></div><div className={`font-black ${adjustment.amount < 0 ? "text-emerald-600" : ""}`}>{money(adjustment.amount, invoice.currency)}</div></div>)}</div></section> : null}
        <div className="ml-auto w-full max-w-sm border border-border p-4 text-sm"><div className="flex justify-between py-1"><span>Subtotal</span><span className="font-bold">{money(invoice.subtotal, invoice.currency)}</span></div><div className="flex justify-between py-1"><span>Discount</span><span className="font-bold">-{money(invoice.discount_amount, invoice.currency)}</span></div><div className="flex justify-between py-1"><span>Tax</span><span className="font-bold">{money(invoice.tax_amount, invoice.currency)}</span></div><div className="mt-2 flex justify-between border-t border-border pt-3 text-base"><span className="font-black">Total</span><span className="font-black">{money(invoice.total, invoice.currency)}</span></div><div className="flex justify-between py-1"><span>Paid</span><span className="font-bold text-emerald-600">{money(invoice.amount_paid, invoice.currency)}</span></div><div className="mt-2 flex justify-between border-t border-border pt-3 text-base"><span className="font-black">Balance Due</span><span className="font-black">{money(invoice.balance_due, invoice.currency)}</span></div></div>
        {invoice.notes ? <section className="border border-border p-4"><div className="text-[10px] font-black uppercase text-muted-foreground">Notes</div><div className="mt-2 whitespace-pre-line text-sm">{invoice.notes}</div></section> : null}
      </div> : null}
      {tab === "labour" ? <LineTable lines={labour} currency={invoice.currency} /> : null}
      {tab === "materials" ? <LineTable lines={materials} currency={invoice.currency} /> : null}
      {tab === "charges" ? <div className="space-y-4"><LineTable lines={charges} currency={invoice.currency} />{adjustments.length > 0 ? <div className="border border-border"><div className="border-b border-border bg-muted/40 px-3 py-2 text-[10px] font-black uppercase text-muted-foreground">Credit notes / adjustments</div>{adjustments.map((adjustment) => <div key={adjustment.id} className="flex items-center justify-between gap-4 border-b border-border p-3 last:border-0"><div><div className="text-sm font-bold">{adjustment.reason}</div><div className="text-[10px] uppercase text-muted-foreground">{adjustment.adjustment_type} · {adjustment.status}</div></div><div className="text-sm font-black">{money(adjustment.amount, invoice.currency)}</div></div>)}</div> : null}</div> : null}
      {tab === "payments" ? <div className="space-y-3">{payments.length === 0 ? <div className="border border-border p-8 text-center text-sm text-muted-foreground">No payments recorded.</div> : payments.map((payment) => <div key={payment.id} className="flex flex-wrap items-center justify-between gap-4 border border-border p-4"><div><div className="text-sm font-black">{payment.payment_method === "tap" ? "Tap" : payment.payment_method === "cash" ? "Cash" : payment.payment_method}</div><div className="mt-1 text-xs text-muted-foreground">{formatDateTime(payment.received_at)}{payment.reference ? ` · ${payment.reference}` : ""}</div>{payment.void_reason ? <div className="mt-1 text-xs text-rose-600">Voided: {payment.void_reason}</div> : null}</div><div className="flex items-center gap-3"><div className="text-right"><div className="text-base font-black">{money(payment.amount, invoice.currency)}</div><div className="text-[10px] font-black uppercase text-muted-foreground">{payment.status}</div></div>{canManageBilling && payment.status === "posted" ? <button type="button" onClick={() => onVoidPayment(payment)} className="no-print border border-rose-500/40 px-2 py-1 text-[10px] font-black text-rose-600">Reverse</button> : null}</div></div>)}</div> : null}
      {tab === "activity" ? <div className="space-y-2">{events.length === 0 ? <div className="border border-border p-8 text-center text-sm text-muted-foreground">No invoice activity yet.</div> : events.map((event) => <div key={event.id} className="border border-border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div className="text-sm font-black">{event.event_type.replaceAll("_", " ")}</div><div className="text-xs text-muted-foreground">{formatDateTime(event.created_at)}</div></div><div className="mt-1 text-xs text-muted-foreground">{event.created_by ? (profileMap.get(event.created_by)?.full_name || profileMap.get(event.created_by)?.email || "User") : "System"}</div></div>)}</div> : null}
    </div>
    <style>{`@media print { body * { visibility: hidden !important; } #fieldops-invoice-print, #fieldops-invoice-print * { visibility: visible !important; } #fieldops-invoice-print { position: absolute !important; left: 0; top: 0; width: 100%; padding: 24px; background: white !important; color: black !important; } .no-print { display: none !important; } }`}</style>
  </ModalShell>;
}
