"use client";
import type { ManualChargeForm } from "../../types";
import { ModalShell } from "../modal-shell";

export function ManualChargeModal({ open, form, error, saving, onChange, onSave, onClose }: { open: boolean; form: ManualChargeForm; error: string | null; saving: boolean; onChange: (form: ManualChargeForm) => void; onSave: () => void; onClose: () => void }) {
  if (!open) return null;
  return <ModalShell title="Add billable charge" eyebrow="Invoice" onClose={onClose} footer={<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="h-10 border border-border px-4 text-sm font-bold">Cancel</button><button type="button" disabled={saving} onClick={onSave} className="h-10 bg-primary px-4 text-sm font-black text-primary-foreground disabled:opacity-60">{saving ? "Adding…" : "Add Charge"}</button></div>}>
    <div className="grid gap-4 md:grid-cols-2"><label><span className="mb-1 block text-xs font-black">Charge type</span><select value={form.lineType} onChange={(e) => onChange({ ...form, lineType: e.target.value as ManualChargeForm["lineType"] })} className="h-11 w-full border border-border bg-card px-3"><option value="service">Service</option><option value="travel">Travel</option><option value="equipment">Equipment</option><option value="other">Other</option></select></label><label><span className="mb-1 block text-xs font-black">Quantity</span><input value={form.quantity} onChange={(e) => onChange({ ...form, quantity: e.target.value })} inputMode="decimal" className="h-11 w-full border border-border bg-card px-3" /></label></div>
    <label className="mt-4 block"><span className="mb-1 block text-xs font-black">Description</span><input value={form.description} onChange={(e) => onChange({ ...form, description: e.target.value })} className="h-11 w-full border border-border bg-card px-3" /></label>
    <div className="mt-4 grid gap-4 md:grid-cols-2"><label><span className="mb-1 block text-xs font-black">Unit price</span><input value={form.unitPrice} onChange={(e) => onChange({ ...form, unitPrice: e.target.value })} inputMode="decimal" className="h-11 w-full border border-border bg-card px-3" placeholder="0.00" /></label><label className="flex items-center gap-3 pt-6"><input type="checkbox" checked={form.taxable} onChange={(e) => onChange({ ...form, taxable: e.target.checked })} className="h-4 w-4" /><span className="text-sm font-bold">Taxable charge</span></label></div>
    {error ? <div className="mt-4 border border-rose-500/40 bg-rose-500/10 p-3 text-sm font-semibold text-rose-700 dark:text-rose-200">{error}</div> : null}
  </ModalShell>;
}
